[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
lib_deps =
    waspinator/AccelStepper @ ^1.64
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/cu.usbserial-A10N20X1
monitor_rts = 0
monitor_dtr = 0
build_src_filter =
    +<main.cpp>
    -<calibration_main.cpp>

[env:nanoatmega328new_calibration]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/cu.usbserial-A10N20X1
monitor_rts = 0
monitor_dtr = 0
build_src_filter =
    +<calibration_main.cpp>
    -<main.cpp>
